up:
	docker compose up -d --build

down:
	docker compose down

logs:
	docker compose logs -f

delete:
	docker compose down -vm

prisma-generate:
	npx prisma generate

prisma-migrate:
	npx prisma migrate dev

prisma-studio:
	npx prisma studio

prisma-push:
	npx prisma db push